theme: jekyll-theme-cayman
title: Behavioral Digital Twins for Smart Cities Workshop
description: In conjunction with IEEE FG 2023, Waikoloa Hawaii, USA  
Jan 4th-8th, 2023
show_downloads: false
google_analytics:
