theme: jekyll-theme-cayman
title: Behavioral Digital Twins for Smart Cities Workshop
description: In conjunction with IEEE FG 2023, Waikoloa Hawaii, USA, from January 5 to 8, 2023
show_downloads: false
google_analytics:
